In [1]:
import pandas as pd
df = pd.read_csv("Spam-classifier Master/spam.csv", encoding="latin1")

# Keep only the first two columns: v1 = label, v2 = message
df = df[['v1', 'v2']]

# Rename columns for clarity
df = df.rename(columns={'v1': 'label', 'v2': 'message'})


In [2]:
df

,label,message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [3]:
# # Data Cleaning and Preprocessing
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\wania\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [4]:
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [5]:
#Using SnowballStemmer
from nltk.stem import SnowballStemmer
snowballstemmer=SnowballStemmer('english')

In [11]:
# Using Lemmatization
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\wania\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [14]:
lemma=WordNetLemmatizer()

In [15]:
corpus=[]
for i in range(0,len(df)):
    review=re.sub('[^a-zA-Z]',' ',df['message'][i])
    review=review.lower()
    review=review.split()
    # review=[ps.stem(word) for word in review if word not in stopwords.words('english')] 
    # review=[snowballstemmer.stem(word) for word in review if word not in stopwords.words('english')]
    review=[lemma.lemmatize(word,pos='v') for word in review if word not in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)

# Create Bag of Words

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)
X=cv.fit_transform(corpus).toarray()

In [17]:
print(X[:5])


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


## For Binary

In [18]:
cv=CountVectorizer(max_features=100,binary=True)
X=cv.fit_transform(corpus).toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [19]:
cv.vocabulary_

{'go': np.int64(24),
 'great': np.int64(26),
 'get': np.int64(22),
 'wat': np.int64(91),
 'ok': np.int64(58),
 'free': np.int64(21),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(29),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(40),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(18),
 'prize': np.int64(64),
 'claim': np.int64(9),
 'call': np.int64(6),
 'mobile': np.int64(49),
 'home': np.int64(31),
 'want': np.int64(90),
 'today': np.int64(82),
 'cash': np.int64(8),
 'day': np.int64(15),
 'reply': np.int64(66),
 'www': np.int64(97),
 'right': np.int64(67),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(81),
 'use': np.int64(88),
 'message': np.int64(47),
 'com': np.int64(10),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(45),
 'way': np.int64(92),
 'feel': np.int64(19),
 'dont': np.int64(17),
 'miss': np.int64

In [20]:
## 

In [25]:
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(1,1))
X=cv.fit_transform(corpus).toarray()
cv.vocabulary_

{'go': np.int64(24),
 'great': np.int64(26),
 'get': np.int64(22),
 'wat': np.int64(91),
 'ok': np.int64(58),
 'free': np.int64(21),
 'win': np.int64(95),
 'text': np.int64(78),
 'txt': np.int64(85),
 'say': np.int64(68),
 'already': np.int64(0),
 'think': np.int64(80),
 'hey': np.int64(29),
 'week': np.int64(93),
 'back': np.int64(4),
 'like': np.int64(40),
 'still': np.int64(74),
 'send': np.int64(70),
 'even': np.int64(18),
 'prize': np.int64(64),
 'claim': np.int64(9),
 'call': np.int64(6),
 'mobile': np.int64(49),
 'home': np.int64(31),
 'want': np.int64(90),
 'today': np.int64(82),
 'cash': np.int64(8),
 'day': np.int64(15),
 'reply': np.int64(66),
 'www': np.int64(97),
 'right': np.int64(67),
 'thank': np.int64(79),
 'take': np.int64(76),
 'time': np.int64(81),
 'use': np.int64(88),
 'message': np.int64(47),
 'com': np.int64(10),
 'oh': np.int64(57),
 'yes': np.int64(99),
 'make': np.int64(45),
 'way': np.int64(92),
 'feel': np.int64(19),
 'dont': np.int64(17),
 'miss': np.int64

In [29]:
cv=CountVectorizer(max_features=200,binary=True,ngram_range=(1,2))
X=cv.fit_transform(corpus).toarray()
cv.vocabulary_

{'go': np.int64(58),
 'great': np.int64(61),
 'get': np.int64(56),
 'wat': np.int64(184),
 'ok': np.int64(120),
 'free': np.int64(52),
 'win': np.int64(189),
 'st': np.int64(154),
 'may': np.int64(98),
 'text': np.int64(163),
 'txt': np.int64(175),
 'dun': np.int64(40),
 'say': np.int64(139),
 'already': np.int64(0),
 'think': np.int64(167),
 'live': np.int64(87),
 'around': np.int64(5),
 'hey': np.int64(70),
 'week': np.int64(187),
 'word': np.int64(191),
 'back': np.int64(9),
 'like': np.int64(85),
 'still': np.int64(156),
 'send': np.int64(141),
 'even': np.int64(44),
 'speak': np.int64(152),
 'per': np.int64(123),
 'friends': np.int64(54),
 'customer': np.int64(32),
 'prize': np.int64(134),
 'claim': np.int64(21),
 'call': np.int64(14),
 'mobile': np.int64(105),
 'co': np.int64(23),
 'gonna': np.int64(59),
 'home': np.int64(73),
 'soon': np.int64(150),
 'want': np.int64(183),
 'talk': np.int64(161),
 'stuff': np.int64(158),
 'tonight': np.int64(173),
 'today': np.int64(170),
 'cash

In [30]:
cv=CountVectorizer(max_features=100,binary=True,ngram_range=(2,3))
X=cv.fit_transform(corpus).toarray()
cv.vocabulary_

{'free entry': np.int64(34),
 'claim call': np.int64(17),
 'call claim': np.int64(3),
 'free call': np.int64(33),
 'chance win': np.int64(16),
 'txt word': np.int64(91),
 'let know': np.int64(54),
 'go home': np.int64(37),
 'please call': np.int64(67),
 'lt gt': np.int64(60),
 'want go': np.int64(97),
 'like lt': np.int64(55),
 'like lt gt': np.int64(56),
 'sorry call': np.int64(81),
 'call later': np.int64(11),
 'sorry call later': np.int64(82),
 'ur award': np.int64(92),
 'come back': np.int64(23),
 'call customer': np.int64(4),
 'customer service': np.int64(25),
 'cash prize': np.int64(15),
 'call customer service': np.int64(5),
 'try contact': np.int64(88),
 'draw show': np.int64(30),
 'show prize': np.int64(79),
 'prize guarantee': np.int64(73),
 'guarantee call': np.int64(43),
 'valid hrs': np.int64(95),
 'draw show prize': np.int64(31),
 'show prize guarantee': np.int64(80),
 'prize guarantee call': np.int64(74),
 'select receive': np.int64(76),
 'private account': np.int64(70),